# Generated by Django 3.2.9 on 2021-11-24 05:50

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('album_mbe', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userfollows',
            unique_together={('user', 'follows')},
        ),
        migrations.DeleteModel(
            name='Caption',
        ),
    ]
